In [6]:

!pip install pandas numpy matplotlib scikit-learn joblib

Requirement already satisfied: pandas in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (2.4.5)
Requirement already satisfied: matplotlib in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (3.10.9)
Requirement already satisfied: scikit-learn in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (1.9.0)
Requirement already satisfied: joblib in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\arshad\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd

# Load the dataset
df = pd.read_csv("spam.csv", encoding="latin-1")

# Display the first 5 rows
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [9]:
print(df.columns)

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='str')

In [10]:
df = df[['v1', 'v2']]

In [11]:
df.columns = ['label', 'text']

In [12]:
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
df.isnull().sum()

label    0
text     0
dtype: int64

In [14]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

In [15]:

df.head()

   label                                               text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [16]:
X = df['text']
y = df['label']

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 4457
Testing samples: 1115

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
vectorizer = TfidfVectorizer(stop_words='english')

In [22]:
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [23]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(4457, 7472)
(1115, 7472)

In [24]:

from sklearn.naive_bayes import MultinomialNB

In [25]:
model = MultinomialNB()

In [26]:
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [27]:
y_pred = model.predict(X_test_tfidf)

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9668161434977578

In [31]:
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 96.68%

In [32]:
from sklearn.metrics import classification_report

In [33]:

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.75      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[965   0]
 [ 37 113]]

In [36]:
message = ["Congratulations! You have won a free iPhone. Claim now!"]

message_vector = vectorizer.transform(message)

prediction = model.predict(message_vector)

if prediction[0] == 1:
    print("Spam")
else:
    print("Ham")

Spam

In [37]:
message = ["Hi, are we meeting at 5 PM today?"]

message_vector = vectorizer.transform(message)

prediction = model.predict(message_vector)

if prediction[0] == 1:
    print("Spam")
else:
    print("Ham")

Ham

In [38]:
import joblib

In [39]:
joblib.dump(model, "model.pkl")

['model.pkl']

In [40]:
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']

In [41]:
loaded_model = joblib.load("model.pkl")
loaded_vectorizer = joblib.load("vectorizer.pkl")

In [42]:
def predict_spam(message):
    message_vector = loaded_vectorizer.transform([message])
    prediction = loaded_model.predict(message_vector)

    if prediction[0] == 1:
        return "Spam"
    else:
        return "Ham"

In [45]:

print(predict_spam("Congratulations! You won a free laptop."))

Ham

In [44]:
print(predict_spam("Can we meet tomorrow at 10 AM?"))

Ham

In [46]:
print(predict_spam("FREE entry into our weekly competition. Call now to claim your prize!"))

Spam

In [48]:
pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'